name: Go

on:
  push:
    branches: [ main,  release/* ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: 0 2 * * 1-5
env:
  GO_VERSION: 1.17.1
  GOLANGCI_LINT_VERSION: v1.42.1
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x,  1.17.x]
        os: [macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: "${{ env.GOLANGCI_LINT_VERSION }}"
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
