name: Go

on:
  push:
    branches: [ main,  release/* ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [macos-latest, windows-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
